name: Build & Push to GHCR

on:
  push:
    branches:
      - deploy

jobs:
  build-push:
    uses: sward-UPC/.github/.github/workflows/build-push-ghcr.yml@main
    with:
      image_name: sward-ms-xai
      service_type: microservice
      aws_service_name: sward-ms-xai
      aws_cluster_name: sward-cluster
      needs_shared: true
    secrets: inherit

