name: Build & Push to GHCR

on:
  push:
    branches:
      - deploy

jobs:
  build-push:
    uses: sward-UPC/.github/.github/workflow-templates/build-push-ghcr.yml@main
    with:
      image_name: sward-ms-xai
      needs_shared: true
    secrets: inherit
